AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DeployBranch:
    Type: String
  DevNameServers:
    Description: 'Comma separated string of Nameserver.'
    Type: String
Conditions:
  IsMaster: !Equals
    - !Ref DeployBranch
    - 'master'
Resources:
  Production:
    Condition: IsMaster
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DevNameServers: !Ref DevNameServers
      TemplateURL: ./stacks/r53/production.yml
      TimeoutInMinutes: 3

