AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Production:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/arn:aws:s3:us-east-1:002232816753:accesspoint/cf-templates/cf-templates/developmentH/3908b465c178a340cb7b58831b220206.template
  Development:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/arn:aws:s3:us-east-1:002232816753:accesspoint/cf-templates/cf-templates/developmentH/093f1eaad2eeffc97d4f638284fb3ff9.template

