AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Production:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cf-templates-3wxecbr0vy4b-us-east-2/master/1376b262cc02b79cdeca6612411eddfb.template

