AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String

Resources:
  Master:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: .stacks/r53/production.yaml
  Development:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: .stacks/r53/development.yaml

