AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Master:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/r53/production.yml
  Development:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/r53/development.yml

