version: 2.1

jobs:
  deploy_cloudformation:
    parameters:
      template:
        default: template.yml
        type: string
      stack:
        default: ${CIRCLE_BRANCH}
        type: string
      dev_nameservers:
        type: string
        default: ""
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      # - when:
      #     condition: <<parameters.nameservers>>
      #     steps:
      #       - package_template:
      #           template: master-template.yml
      # - unless:
      #     condition: <<parameters.nameservers>>
      #     steps:
      #       - package_template:
      #           template: <<parameters.template>>
      - package_template:
          template: <<parameters.template>>
      - deploy_template:
          stack: <<parameters.stack>>
          dev_nameservers: <<parameters.dev_nameservers>>
      # - when:
      #     condition: <<parameters.dev_nameservers>>
      #     steps:
      #       - deploy_template:
      #           stack: <<parameters.stack>>
      #           dev_nameservers: <<parameters.dev_nameservers>>
      # - unless:
      #     condition: <<parameters.dev_nameservers>>
      #     steps:
      #       - deploy_template:
      #           stack: <<parameters.stack>>
      #           dev_nameservers: <<parameters.dev_nameservers>>
commands:
  package_template:
    parameters:
      template:
        type: string
    steps:
      - run: echo <<parameters.template>>
      - run:
          command: >
            aws cloudformation package
            --template-file << parameters.template >>
            --s3-bucket cf-templates-3wxecbr0vy4b-us-east-2
            --s3-prefix $CIRCLE_BRANCH
            --output-template-file packaged.yml
  deploy_template:
    parameters:
      stack:
        type: string
      dev_nameservers:
        type: string
        default: ""
    steps:
      - run:
          command: >
            aws cloudformation deploy
            --template-file ./packaged.yml
            --capabilities CAPABILITY_IAM
            --stack-name <<parameters.stack>>
            --no-fail-on-empty-changeset
            --region us-east-2
            --parameter-overrides "DevNameServers=<<parameters.dev_nameservers>>" "DeployBranch=<<parameter.stack>>"
workflows:
  version: 2
  deploy_cloudformation:
    jobs:
      - deploy_cloudformation:
          name: deploy_to_prod
          filters:
            branches:
              only: master
      - deploy_cloudformation:
          name: deploy_to_dev
          filters:
            branches:
              only: development


