version: 2.1

jobs:
  deploy_cloudformation:
    parameters:
      template:
        default: template.yml
        type: string
      stack:
        default: ${CIRCLE_BRANCH}
        type: string
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: Cloudformation package
          command: >
            aws cloudformation package
            --template-file << parameters.template >>
            --s3-bucket addinfantitem
            --s3-prefix $CIRCLE_BRANCH
            --output-template-file packaged.yml
      - run:
          name: Cloudformation deploy
          command: >
            aws cloudformation deploy
            --template-file ./packaged.yml
            --stack-name << parameters.stack >>
            --no-fail-on-empty-changeset
            --region us-east-2


workflows:
  version: 2
  deploy_pgacom_prod:
    jobs:
      - deploy_cloudformation:
        name: deploy-domains
        context: pgacom-prod
        filters:
          branches:
            only: master
      - deploy_cloudformation:
        name: deploy_to_dev
        context: develop
        filters:
          branches:
            only: development


