AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DevNameServers:
    Description: 'Comma separated string of Nameserver.'
    Type: String
Resources:
  DevelopmentNameServers:
    Type: AWS::Route53::RecordSet
    Properties:
      #HostedZoneId: Z2UH9G8UNVTL3A
      HostedZoneName: addinfantitem.com.
      Name: dev.addinfantitem.com
      Type: NS
      TTL: '1800'
      #Name: !Sub 'dev.${HostedZoneName}'
      ResourceRecords: !Split [",", !Ref DevNameServers]